import { useEffect, useMemo, useState } from 'react'
import axios from 'axios'
import { Alert, Button, Card, Col, Form, Row, Spinner, Table } from 'react-bootstrap'
import { useNavigate, useParams } from 'react-router-dom'
import AppSelect, { type AppSelectOption } from '../components/AppSelect'
import { getDisplayName, getUser } from '../utils/auth'
import { normalizeLocationsResponse, type LocationPoint } from '../utils/claims'

type ClaimForm = {
  employee: string
  purpose: string
  departure_date: string
  return_date: string
  origin: string
  destination: string
}

type AllowanceRow = {
  id: number
  allowance: string
  quantity: string
  amount: string
  autoGenerated?: boolean
}

type AllowanceOption = {
  id: number | string
  title?: string
  name?: string
  label?: string
  cost?: number
  nature?: string | null
  grade_range?: string | null
  status?: string | number | null
}

type Employee = {
  id: number | string
  user_id?: number | string
  first_name?: string
  surname?: string
  name?: string
  full_name?: string
  grade?: number | string
  grade_range?: string | null
}

type ClaimDetail = {
  id: number | string
  employee_id?: number | string
  purpose?: string
  departure_date?: string
  return_date?: string
  origin?: string
  destination?: string
  user_distance?: number
  nights?: number
  days?: number
}

type ClaimLine = {
  id?: number | string
  claim_id?: number | string
  allowance_id?: number | string
  quantity?: number
  amount?: number
}

const EMPLOYEES_ENDPOINT = '/api/employee/'
const CITIES_ENDPOINT = '/api/cities/'
const ALLOWANCES_ENDPOINT = '/api/allowances/'
const CLAIMS_ENDPOINT = '/api/claims/'
const CLAIM_LINES_ENDPOINT = '/api/claim-lines/'
const FORM_REQUEST_TIMEOUT_MS = 15000

const initialClaimForm: ClaimForm = {
  employee: '',
  purpose: '',
  departure_date: '',
  return_date: '',
  origin: '',
  destination: '',
}

const createAllowanceRow = (id: number): AllowanceRow => ({
  id,
  allowance: '',
  quantity: '',
  amount: '',
})

const isActiveAllowance = (allowance: AllowanceOption): boolean => {
  if (allowance.status === undefined || allowance.status === null || allowance.status === '') {
    return true
  }

  const status = String(allowance.status).trim().toUpperCase()
  return status === '1' || status === 'ACTIVE'
}

const deriveGradeRange = (grade: number | string | undefined): string | null => {
  if (grade === undefined || grade === null || grade === '') {
    return null
  }

  const numeric = Number(grade)
  if (Number.isNaN(numeric)) {
    return null
  }
  if (numeric >= 1 && numeric <= 4) {
    return 'LOWER'
  }
  if (numeric >= 5 && numeric <= 8) {
    return 'MIDDLE'
  }
  if (numeric >= 9 && numeric <= 12) {
    return 'UPPER'
  }

  return null
}

const toRadians = (value: number) => (value * Math.PI) / 180

const haversineDistanceKm = (
  origin: Pick<LocationPoint, 'latitude' | 'longitude'>,
  destination: Pick<LocationPoint, 'latitude' | 'longitude'>,
) => {
  const radiusKm = 6371
  const dLat = toRadians(destination.latitude - origin.latitude)
  const dLon = toRadians(destination.longitude - origin.longitude)
  const lat1 = toRadians(origin.latitude)
  const lat2 = toRadians(destination.latitude)

  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))

  return radiusKm * c
}

const getMealPeriodCounts = (departureDateTime: string, returnDateTime: string) => {
  if (!departureDateTime || !returnDateTime) {
    return { breakfast: 0, lunch: 0, dinner: 0 }
  }

  const departure = new Date(departureDateTime)
  const returned = new Date(returnDateTime)

  if (
    Number.isNaN(departure.getTime()) ||
    Number.isNaN(returned.getTime()) ||
    returned <= departure
  ) {
    return { breakfast: 0, lunch: 0, dinner: 0 }
  }

  const counts = {
    breakfast: 0,
    lunch: 0,
    dinner: 0,
  }
  const cursor = new Date(departure)
  cursor.setHours(0, 0, 0, 0)

  while (cursor <= returned) {
    const checkpoints = [
      { key: 'breakfast' as const, hour: 10, minute: 0 },
      { key: 'lunch' as const, hour: 13, minute: 0 },
      { key: 'dinner' as const, hour: 19, minute: 0 },
    ]

    checkpoints.forEach(({ key, hour, minute }) => {
      const point = new Date(cursor)
      point.setHours(hour, minute, 0, 0)
      if (point >= departure && point <= returned) {
        counts[key] += 1
      }
    })

    cursor.setDate(cursor.getDate() + 1)
  }

  return counts
}

const pickAllowanceForNature = (
  allowances: AllowanceOption[],
  nature: string,
  gradeRange: string | null,
): AllowanceOption | null => {
  const activeAllowances = allowances.filter(
    (allowance) => isActiveAllowance(allowance) && String(allowance.nature ?? '') === nature,
  )

  if (gradeRange) {
    const exactMatch = activeAllowances.find(
      (allowance) => String(allowance.grade_range ?? '') === gradeRange,
    )
    if (exactMatch) {
      return exactMatch
    }
  }

  const genericMatch = activeAllowances.find(
    (allowance) => allowance.grade_range === null || allowance.grade_range === undefined || allowance.grade_range === '',
  )

  return genericMatch ?? activeAllowances[0] ?? null
}

const normalizeEmployeesResponse = (payload: unknown): Employee[] => {
  if (Array.isArray(payload)) {
    return payload as Employee[]
  }

  if (payload && typeof payload === 'object') {
    const record = payload as Record<string, unknown>

    if (Array.isArray(record.data)) {
      return record.data as Employee[]
    }

    if (Array.isArray(record.results)) {
      return record.results as Employee[]
    }

    if (Array.isArray(record.employees)) {
      return record.employees as Employee[]
    }
  }

  return []
}

const normalizeAllowancesResponse = (payload: unknown): AllowanceOption[] => {
  if (Array.isArray(payload)) {
    return payload as AllowanceOption[]
  }

  if (payload && typeof payload === 'object') {
    const record = payload as Record<string, unknown>

    if (Array.isArray(record.data)) {
      return record.data as AllowanceOption[]
    }

    if (Array.isArray(record.results)) {
      return record.results as AllowanceOption[]
    }

    if (Array.isArray(record.allowances)) {
      return record.allowances as AllowanceOption[]
    }
  }

  return []
}

const getAllowanceLabel = (allowance: AllowanceOption): string => {
  const label = allowance.title?.trim() || allowance.name?.trim() || allowance.label?.trim()
  return label || `Allowance ${allowance.id}`
}

const normalizeClaimLinesResponse = (payload: unknown): ClaimLine[] => {
  if (Array.isArray(payload)) {
    return payload as ClaimLine[]
  }

  if (payload && typeof payload === 'object') {
    const record = payload as Record<string, unknown>

    if (Array.isArray(record.data)) {
      return record.data as ClaimLine[]
    }

    if (Array.isArray(record.results)) {
      return record.results as ClaimLine[]
    }

    if (Array.isArray(record.claim_lines)) {
      return record.claim_lines as ClaimLine[]
    }
  }

  return []
}

const fetchClaimLines = async (claimId: string): Promise<ClaimLine[]> => {
  try {
    const response = await axios.get(`${CLAIMS_ENDPOINT}${claimId}/lines/`)
    const lines = normalizeClaimLinesResponse(response.data)
    return lines.filter((line) => String(line.claim_id ?? claimId) === String(claimId))
  } catch (error) {
    console.warn('Claim lines not available at /claims/:id/lines/.', error)
  }

  try {
    const response = await axios.get(`${CLAIM_LINES_ENDPOINT}?claim_id=${claimId}`)
    const lines = normalizeClaimLinesResponse(response.data)
    return lines.filter((line) => String(line.claim_id ?? claimId) === String(claimId))
  } catch (error) {
    console.warn('Claim lines not available at /claim-lines/.', error)
  }

  return []
}

const getTripValues = (departureDateTime: string, returnDateTime: string) => {
  if (!departureDateTime || !returnDateTime) {
    return { nights: 0, days: 0 }
  }

  const departure = new Date(departureDateTime)
  const returned = new Date(returnDateTime)

  if (
    Number.isNaN(departure.getTime()) ||
    Number.isNaN(returned.getTime()) ||
    returned <= departure
  ) {
    return { nights: 0, days: 0 }
  }

  const oneDayMs = 1000 * 60 * 60 * 24
  const differenceMs = returned.getTime() - departure.getTime()
  const days = Math.ceil(differenceMs / oneDayMs)
  const nights = Math.max(0, Math.floor(differenceMs / oneDayMs))

  return { nights, days }
}

const toDateTimeLocal = (value?: string): string => {
  if (!value) {
    return ''
  }
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) {
    return ''
  }
  const offsetMs = date.getTimezoneOffset() * 60 * 1000
  const local = new Date(date.getTime() - offsetMs)
  return local.toISOString().slice(0, 16)
}

function CreateClaim() {
  const navigate = useNavigate()
  const { id: claimId } = useParams()
  const isEditing = Boolean(claimId)
  const currentUser = getUser()
  const currentUserId = String(currentUser?.id ?? '')
  const [formData, setFormData] = useState<ClaimForm>(initialClaimForm)
  const [allowances, setAllowances] = useState<AllowanceRow[]>([createAllowanceRow(1)])
  const [currentEmployeeId, setCurrentEmployeeId] = useState<string>('')
  const [currentEmployeeGradeRange, setCurrentEmployeeGradeRange] = useState<string | null>(null)
  const [locations, setLocations] = useState<LocationPoint[]>([])
  const [allowanceOptions, setAllowanceOptions] = useState<AllowanceOption[]>([])
  const [nextAllowanceId, setNextAllowanceId] = useState(2)
  const [loadingOptions, setLoadingOptions] = useState(false)
  const [loadError, setLoadError] = useState<string | null>(null)
  const [loadingClaim, setLoadingClaim] = useState(false)
  const [savingClaim, setSavingClaim] = useState(false)
  const [submitError, setSubmitError] = useState<string | null>(null)
  const [submitSuccess, setSubmitSuccess] = useState<string | null>(null)
  const cityOptions = useMemo(() => {
    const values = [
      formData.origin,
      formData.destination,
      ...locations.map((location) => location.name),
    ]
      .map((value) => value.trim())
      .filter((value) => value.length > 0)

    return Array.from(new Set(values))
  }, [formData.destination, formData.origin, locations])
  const citySelectOptions = useMemo<AppSelectOption[]>(
    () => cityOptions.map((city) => ({ value: city, label: city })),
    [cityOptions],
  )
  const allowanceSelectOptions = useMemo<AppSelectOption[]>(
    () =>
      allowanceOptions.map((allowance) => ({
        value: String(allowance.id),
        label: getAllowanceLabel(allowance),
      })),
    [allowanceOptions],
  )
  const locationByName = useMemo(
    () =>
      new Map(
        locations.map((location) => [location.name.trim().toLowerCase(), location] as const),
      ),
    [locations],
  )

  useEffect(() => {
    const fetchOptions = async () => {
      setLoadingOptions(true)
      setLoadError(null)

      try {
        const [allowancesResult, employeesResult, citiesResult] = await Promise.allSettled([
          axios.get(ALLOWANCES_ENDPOINT, { timeout: FORM_REQUEST_TIMEOUT_MS }),
          axios.get(EMPLOYEES_ENDPOINT, { timeout: FORM_REQUEST_TIMEOUT_MS }),
          axios.get(CITIES_ENDPOINT, { timeout: FORM_REQUEST_TIMEOUT_MS }),
        ])

        if (allowancesResult.status !== 'fulfilled') {
          throw allowancesResult.reason
        }

        setAllowanceOptions(normalizeAllowancesResponse(allowancesResult.value.data))

        const normalizedEmployees =
          employeesResult.status === 'fulfilled'
            ? normalizeEmployeesResponse(employeesResult.value.data)
            : []
        const matchedEmployee = normalizedEmployees.find(
          (employee) => String(employee.user_id ?? '') === currentUserId,
        )
        setCurrentEmployeeId(matchedEmployee ? String(matchedEmployee.id) : '')
        setCurrentEmployeeGradeRange(
          matchedEmployee?.grade_range ?? deriveGradeRange(matchedEmployee?.grade),
        )

        const normalizedCities =
          citiesResult.status === 'fulfilled'
            ? normalizeLocationsResponse(citiesResult.value.data)
            : []
        setLocations(normalizedCities)
      } catch (error) {
        setLoadError('Failed to load employees, cities, and allowances.')
        console.error(error)
      } finally {
        setLoadingOptions(false)
      }
    }

    void fetchOptions()
  }, [currentUserId])

  useEffect(() => {
    if (!claimId) {
      return
    }

    const fetchClaim = async () => {
      setLoadingClaim(true)
      setLoadError(null)

      try {
        const [claimResponse, claimLines] = await Promise.all([
          axios.get<ClaimDetail>(`${CLAIMS_ENDPOINT}${claimId}/`),
          fetchClaimLines(claimId),
        ])

        const claim = claimResponse.data
        setFormData({
          employee: claim.employee_id !== undefined ? String(claim.employee_id) : '',
          purpose: claim.purpose ?? '',
          departure_date: toDateTimeLocal(claim.departure_date),
          return_date: toDateTimeLocal(claim.return_date),
          origin: claim.origin ?? '',
          destination: claim.destination ?? '',
        })

        if (claimLines.length > 0) {
          const mappedRows = claimLines.map((line, index) => {
            const allowanceId = line.allowance_id !== undefined ? String(line.allowance_id) : ''
            const matchedAllowance = allowanceOptions.find(
              (option) => String(option.id) === allowanceId,
            )
            const amount =
              line.amount !== undefined
                ? String(line.amount)
                : matchedAllowance?.cost !== undefined
                  ? String(matchedAllowance.cost)
                  : ''

            return {
              id: index + 1,
              allowance: allowanceId,
              quantity: line.quantity !== undefined ? String(line.quantity) : '',
              amount,
            }
          })
          setAllowances(mappedRows)
          setNextAllowanceId(mappedRows.length + 1)
        }
      } catch (error) {
        setLoadError('Failed to load claim details.')
        console.error(error)
      } finally {
        setLoadingClaim(false)
      }
    }

    void fetchClaim()
  }, [claimId])

  useEffect(() => {
    if (!isEditing || allowanceOptions.length === 0) {
      return
    }

    setAllowances((previous) =>
      previous.map((row) => {
        if (row.amount) {
          return row
        }
        const matched = allowanceOptions.find(
          (option) => String(option.id) === String(row.allowance),
        )
        if (!matched || matched.cost === undefined) {
          return row
        }
        return { ...row, amount: String(matched.cost) }
      }),
    )
  }, [isEditing, allowanceOptions])

  const { nights, days } = useMemo(
    () => getTripValues(formData.departure_date, formData.return_date),
    [formData.departure_date, formData.return_date],
  )
  const mealCounts = useMemo(
    () => getMealPeriodCounts(formData.departure_date, formData.return_date),
    [formData.departure_date, formData.return_date],
  )
  const roundTripDistanceKm = useMemo(() => {
    if (!formData.origin || !formData.destination) {
      return 0
    }

    const origin = locationByName.get(formData.origin.trim().toLowerCase())
    const destination = locationByName.get(formData.destination.trim().toLowerCase())

    if (!origin || !destination) {
      return 0
    }

    return haversineDistanceKm(origin, destination) * 2
  }, [formData.destination, formData.origin, locationByName])
  const autoAllowanceRows = useMemo(() => {
    if (isEditing || !formData.departure_date || !formData.return_date) {
      return [] as AllowanceRow[]
    }

    const candidates = [
      {
        nature: 'BREAKFAST',
        quantity: mealCounts.breakfast,
      },
      {
        nature: 'LUNCH',
        quantity: mealCounts.lunch,
      },
      {
        nature: 'DINNER',
        quantity: mealCounts.dinner,
      },
      {
        nature: 'OUT_OF_STATION',
        quantity: nights,
      },
      {
        nature: 'FUEL',
        quantity: roundTripDistanceKm / 5,
      },
    ]

    return candidates
      .filter((candidate) => candidate.quantity > 0)
      .map((candidate, index) => {
        const matchedAllowance = pickAllowanceForNature(
          allowanceOptions,
          candidate.nature,
          currentEmployeeGradeRange ?? null,
        )

        if (!matchedAllowance) {
          return null
        }

        return {
          id: index + 1,
          allowance: String(matchedAllowance.id),
          quantity:
            Number.isInteger(candidate.quantity)
              ? String(candidate.quantity)
              : candidate.quantity.toFixed(2),
          amount:
            matchedAllowance.cost !== undefined && matchedAllowance.cost !== null
              ? String(matchedAllowance.cost)
              : '',
          autoGenerated: true,
        } satisfies AllowanceRow
      })
      .filter((row): row is AllowanceRow => row !== null)
  }, [
    allowanceOptions,
    currentEmployeeGradeRange,
    formData.departure_date,
    formData.return_date,
    isEditing,
    mealCounts.breakfast,
    mealCounts.dinner,
    mealCounts.lunch,
    nights,
    roundTripDistanceKm,
  ])

  const allowancesTotal = useMemo(() => {
    return allowances.reduce((total, row) => {
      const quantity = Number(row.quantity) || 0
      const amount = Number(row.amount) || 0
      return total + quantity * amount
    }, 0)
  }, [allowances])

  const handleInputChange = (
    event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>,
  ) => {
    const { name, value } = event.target
    setFormData((previous) => ({ ...previous, [name]: value }))
  }

  const handleCityChange = (field: 'origin' | 'destination', value: string) => {
    setFormData((previous) => ({
      ...previous,
      [field]: value,
    }))
  }

  useEffect(() => {
    if (isEditing) {
      return
    }

    setAllowances((previous) => {
      const manualRows = previous.filter(
        (row) =>
          !row.autoGenerated && (row.allowance || row.quantity || row.amount),
      )
      const mergedRows = [...autoAllowanceRows, ...manualRows].map((row, index) => ({
        ...row,
        id: index + 1,
      }))

      if (mergedRows.length === 0) {
        return [createAllowanceRow(1)]
      }

      return mergedRows
    })
  }, [autoAllowanceRows, isEditing])

  useEffect(() => {
    const maxId = allowances.reduce((highest, row) => Math.max(highest, row.id), 0)
    setNextAllowanceId(maxId + 1)
  }, [allowances])

  const handleAllowanceChange = (
    id: number,
    field: keyof Pick<AllowanceRow, 'allowance' | 'quantity' | 'amount'>,
    value: string,
  ) => {
    setAllowances((previous) =>
      previous.map((row) => {
        if (row.id !== id) {
          return row
        }

        if (field === 'allowance') {
          const matched = allowanceOptions.find((option) => String(option.id) === String(value))
          const amount = matched?.cost !== undefined ? String(matched.cost) : ''
          return { ...row, allowance: value, amount }
        }

        return { ...row, [field]: value }
      }),
    )
  }

  const addAllowanceRow = () => {
    setAllowances((previous) => [...previous, createAllowanceRow(nextAllowanceId)])
    setNextAllowanceId((previous) => previous + 1)
  }

  const removeAllowanceRow = (id: number) => {
    setAllowances((previous) => {
      if (previous.length === 1) {
        return previous
      }
      return previous.filter((row) => row.id !== id)
    })
  }

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setSavingClaim(true)
    setSubmitError(null)
    setSubmitSuccess(null)

    if (!isEditing && !currentEmployeeId) {
      setSubmitError('Your employee profile could not be resolved from the current account.')
      setSavingClaim(false)
      return
    }

    if (!formData.origin || !formData.destination) {
      setSubmitError('Please choose both origin and destination.')
      setSavingClaim(false)
      return
    }

    if (allowances.some((row) => !row.allowance)) {
      setSubmitError('Please choose an allowance for every row.')
      setSavingClaim(false)
      return
    }

    const parseId = (value: string) => {
      const numeric = Number(value)
      return Number.isNaN(numeric) ? value : numeric
    }

    const allowancePayload = allowances
      .filter((row) => row.allowance)
      .map((row) => ({
        allowance_id: parseId(row.allowance),
        quantity: Number(row.quantity) || 0,
        amount: Number(row.amount) || 0,
      }))

    const payload = {
      purpose: formData.purpose.trim(),
      departure_date: formData.departure_date,
      return_date: formData.return_date,
      origin: formData.origin,
      destination: formData.destination,
      nights,
      days,
      total_allowances: allowancesTotal,
      allowances: allowancePayload,
      auto_distance: true,
      ...(isEditing ? { employee_id: parseId(formData.employee) } : {}),
    }

    try {
      const response = isEditing
        ? await axios.put(`${CLAIMS_ENDPOINT}${claimId}/`, payload)
        : await axios.post(CLAIMS_ENDPOINT, payload)
      console.log('Save claim response:', response.data)
      setSubmitSuccess(isEditing ? 'Claim updated successfully.' : 'Claim submitted successfully.')
      navigate('/my-claims')
    } catch (error) {
      setSubmitError(isEditing ? 'Failed to update claim.' : 'Failed to submit claim.')
      console.error(error)
    } finally {
      setSavingClaim(false)
    }
  }

  return (
    <div>
      <div className='mb-4'>
        <h2 className='page-title'>{isEditing ? 'Edit Claim' : 'Create Claim'}</h2>
        <p className='page-subtitle'>Capture trip details, allowances, and submit for review.</p>
      </div>
      <div className='row'>
        <div className='col-12'>
          <Card>
            <Card.Body>
              <h5 className='mb-3'>Trip Details</h5>
            {loadError ? <Alert variant='danger'>{loadError}</Alert> : null}
            {submitError ? <Alert variant='danger'>{submitError}</Alert> : null}
            {submitSuccess ? <Alert variant='success'>{submitSuccess}</Alert> : null}
            {loadingOptions || loadingClaim ? (
              <div className='d-flex align-items-center mb-3'>
                <Spinner animation='border' size='sm' className='me-2' />
                <span>
                  {loadingClaim
                    ? 'Loading claim details...'
                    : 'Loading employees, cities, and allowances...'}
                </span>
              </div>
            ) : null}
            <Form onSubmit={handleSubmit}>
              <Row className='mb-3'>
                <Col md={12}>
                  <div className='p-3 rounded border bg-light-subtle'>
                    <div className='text-muted small mb-1'>Claim Owner</div>
                    <strong>{getDisplayName(currentUser)}</strong>
                    <div className='text-muted small'>
                      This claim will be created under your logged-in employee account.
                    </div>
                  </div>
                </Col>
              </Row>

              <Row className='mb-3'>
                <Form.Group as={Col} md={12} controlId='claimPurpose'>
                  <Form.Label>Purpose</Form.Label>
                  <Form.Control
                    as='textarea'
                    rows={1}
                    name='purpose'
                    value={formData.purpose}
                    onChange={handleInputChange}
                    placeholder='Trip purpose'
                    required
                  />
                </Form.Group>
              </Row>

              <Row className='mb-3'>
                <Form.Group as={Col} md={4} controlId='claimDepartureDate'>
                  <Form.Label>Departure Date & Time</Form.Label>
                  <Form.Control
                    type='datetime-local'
                    name='departure_date'
                    value={formData.departure_date}
                    onChange={handleInputChange}
                    step={60}
                    required
                  />
                </Form.Group>

                <Form.Group as={Col} md={4} controlId='claimReturnDate'>
                  <Form.Label>Return Date & Time</Form.Label>
                  <Form.Control
                    type='datetime-local'
                    name='return_date'
                    value={formData.return_date}
                    onChange={handleInputChange}
                    min={formData.departure_date || undefined}
                    step={60}
                    required
                  />
                </Form.Group>

                <Form.Group as={Col} md={2} controlId='claimNights'>
                  <Form.Label>Nights</Form.Label>
                  <Form.Control value={nights} readOnly />
                </Form.Group>

                <Form.Group as={Col} md={2} controlId='claimDays'>
                  <Form.Label>Days</Form.Label>
                  <Form.Control value={days} readOnly />
                </Form.Group>
              </Row>

              <Row className='mb-4'>
                <Form.Group as={Col} md={4} controlId='claimOrigin'>
                  <Form.Label>Origin</Form.Label>
                  <AppSelect
                    inputId='claimOrigin'
                    options={citySelectOptions}
                    value={formData.origin}
                    onChange={(value) => handleCityChange('origin', value)}
                    isDisabled={loadingOptions}
                    isClearable
                    placeholder='Choose origin...'
                  />
                </Form.Group>

                <Form.Group as={Col} md={4} controlId='claimDestination'>
                  <Form.Label>Destination</Form.Label>
                  <AppSelect
                    inputId='claimDestination'
                    options={citySelectOptions}
                    value={formData.destination}
                    onChange={(value) => handleCityChange('destination', value)}
                    isDisabled={loadingOptions}
                    isClearable
                    placeholder='Choose destination...'
                  />
                </Form.Group>
                <Col md={4} className='d-flex align-items-end'>
                  <div className='text-muted small'>
                    Distance is calculated automatically.
                  </div>
                </Col>
              </Row>


              <div className='d-flex justify-content-between align-items-center mb-2'>
                <h6 className='mb-0'>Allowances</h6>
                <Button variant='outline-primary' onClick={addAllowanceRow} type='button' size='sm'>
                  Add Row
                </Button>
              </div>

              <Table hover>
                <thead>
                  <tr>
                    <th style={{ width: '40%' }}>Allowance</th>
                    <th style={{ width: '20%' }}>Quantity</th>
                    <th style={{ width: '20%' }}>Amount</th>
                    <th style={{ width: '20%' }}>Row Total</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {allowances.map((row) => {
                    const quantity = Number(row.quantity) || 0
                    const amount = Number(row.amount) || 0
                    const rowTotal = quantity * amount

                    return (
                      <tr key={row.id}>
                        <td>
                          <AppSelect
                            inputId={`claimAllowance${row.id}`}
                            value={row.allowance}
                            options={allowanceSelectOptions}
                            onChange={(value) => handleAllowanceChange(row.id, 'allowance', value)}
                            isDisabled={loadingOptions}
                            placeholder='Choose allowance...'
                          />
                        </td>
                        <td>
                          <Form.Control
                            type='number'
                            min='0'
                            step='0.01'
                            value={row.quantity}
                            onChange={(event) =>
                              handleAllowanceChange(row.id, 'quantity', event.target.value)
                            }
                            required
                          />
                        </td>
                        <td>
                          <Form.Control
                            type='number'
                            min='0'
                            step='0.01'
                            value={row.amount}
                            onChange={(event) =>
                              handleAllowanceChange(row.id, 'amount', event.target.value)
                            }
                            readOnly
                            required
                          />
                        </td>
                        <td className='align-middle'>{rowTotal.toFixed(2)}</td>
                        <td className='align-middle'>
                          <Button
                            variant='outline-danger'
                            size='sm'
                            type='button'
                            onClick={() => removeAllowanceRow(row.id)}
                            disabled={allowances.length === 1}
                          >
                            Remove
                          </Button>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </Table>

              <div className='d-flex justify-content-end mb-3'>
                <div>
                  <strong>Total Allowances: {allowancesTotal.toFixed(2)}</strong>
                </div>
              </div>

              <div className='d-flex justify-content-end'>
                <Button type='submit' variant='primary' disabled={savingClaim || loadingOptions}>
                  {savingClaim ? 'Saving...' : 'Save Claim'}
                </Button>
              </div>
            </Form>
            </Card.Body>
          </Card>
        </div>
      </div>
    </div>
  )
}

export default CreateClaim


